In [1]:
import numpy as np

In [2]:
#создадим матрицу, которая нам понадобится в работе.
m = np.matrix('1 2 3 4; 5 6 7 8 ; 9 1 5 7')

In [3]:
print(m)

[[1 2 3 4]
 [5 6 7 8]
 [9 1 5 7]]


In [4]:
type(m)


numpy.matrix

In [5]:
#Matix можно превратить в ndarray вот так
m = np.array(m)

In [6]:
type(m)

numpy.ndarray

In [7]:
print(m)

[[1 2 3 4]
 [5 6 7 8]
 [9 1 5 7]]


In [8]:
#Для определения размерности массива Numpy используйте атрибут shape
m.shape

(3, 4)

In [9]:
m.max()
np.max(m)

9

In [10]:
m.max(axis=1)

array([4, 8, 9])

In [11]:
m.max(axis=0)

array([9, 6, 7, 8])

In [12]:
m

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 1, 5, 7]])

In [13]:
m[2,2]

5

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 1, 5, 7]])

In [14]:
np.random.randint(0, 5, 3)

array([1, 4, 0])

In [15]:
np.empty(5) # одномерный массив из пяти элементов, память для которого выделена, но не инициализирована

#np.zeros((10, 7)) # массив размером 10x7, заполненный нулями 
#np.ones((3,3,3)) # массив размером 3х3х3, заполненный единицами 
np.eye(3) # единичная матрица (элементы главной диагонали равны 1, остальные — 0) размера 3х3
#np.full((3, 5), 3.14)  # массив 3x5 заполненный числом 3.14
#np.arange(0, 21, 7)  # одномерный массив, заполненный числами в диапазоне от 0 до 20 с шагом 7
#np.linspace(0, 1, 5)  # массив из пяти чисел, равномерно распределённых в интервале между 0 и 1 включительно
#np.random.randint(0, 10, (3, 3))  # массив размера 3х3, заполненный случайными числами из диапазона от 0 до 9 (включительно)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
np.array([[8,13,18,4], [25,3,18,28], [14,15,18,24], [1,2,3,4]]) 

array([[ 8, 13, 18,  4],
       [25,  3, 18, 28],
       [14, 15, 18, 24],
       [ 1,  2,  3,  4]])

In [17]:
my_secret = [x for x in range(1, 301, 7) if x%10 == 7 or x%10 == 1]
np.array([my_secret, [x/2 for x in my_secret], [x-100 for x in my_secret]])
#Какие элементы расположены в последнем столбце массива, заданного с помощью кода выше?

array([[  1. ,  57. ,  71. , 127. , 141. , 197. , 211. , 267. , 281. ],
       [  0.5,  28.5,  35.5,  63.5,  70.5,  98.5, 105.5, 133.5, 140.5],
       [-99. , -43. , -29. ,  27. ,  41. ,  97. , 111. , 167. , 181. ]])

In [18]:
np.full((5,5), 1)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [19]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
np.array([[1,2,3,4,5], [5,1,2,3,4], [4,5,1,2,3], [3,4,5,1,2], [2,3,4,5,1]])

array([[1, 2, 3, 4, 5],
       [5, 1, 2, 3, 4],
       [4, 5, 1, 2, 3],
       [3, 4, 5, 1, 2],
       [2, 3, 4, 5, 1]])

In [21]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [22]:
np.ones((4, 4), dtype=float)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [23]:

#Какие из вариантов кода можно использовать для создания массива, заполненного нечётными числами?
np.array([i for i in range(11) if i%2])
np.arange(1, 14, 2)

array([ 1,  3,  5,  7,  9, 11, 13])

In [29]:
my_array = np.array([x for x in range(10)])
my_array[5]
my_array[-1]
my_array[3:6]
my_array[1:8:3]

array([1, 4, 7])

In [47]:
my_array = np.array([[1,2,3,4], [10,11,12,13], [45,46,47,48]])
#my_array[2]
my_array[:1,2]
my_array

array([[ 1,  2,  3,  4],
       [10, 11, 12, 13],
       [45, 46, 47, 48]])

In [46]:
my_array[:-1]

array([[ 1,  2,  3,  4],
       [10, 11, 12, 13]])

In [59]:
my_array[:,3]

array([ 4, 13, 48])

Потренируемся извлекать из двумерного массива отдельные элементы и их срезы и производить над ними математические действия. Задания блока будем выполнять на примере массива, созданного кодом:

In [128]:
first_line = [x*y for x in range(2, 100, 6) for y in range (7, 1, -2)]
second_line = [x ** 0.5 for x in range(1000, 1101, 2)]
third_line = [x**2 for x in range(51)]

big_secret = np.array([first_line, second_line, third_line, second_line, first_line])

In [129]:
big_secret[:,50:51] #.sum()

array([[ 294.       ],
       [  33.1662479],
       [2500.       ],
       [  33.1662479],
       [ 294.       ]])

In [130]:
big_secret[:,50]    #.sum()

array([ 294.       ,   33.1662479, 2500.       ,   33.1662479,
        294.       ])

In [131]:
big_secret.shape[(1)]



51

In [132]:
b = big_secret[:, 50]
b

array([ 294.       ,   33.1662479, 2500.       ,   33.1662479,
        294.       ])

In [133]:
big_secret

array([[1.40000000e+01, 1.00000000e+01, 6.00000000e+00, 5.60000000e+01,
        4.00000000e+01, 2.40000000e+01, 9.80000000e+01, 7.00000000e+01,
        4.20000000e+01, 1.40000000e+02, 1.00000000e+02, 6.00000000e+01,
        1.82000000e+02, 1.30000000e+02, 7.80000000e+01, 2.24000000e+02,
        1.60000000e+02, 9.60000000e+01, 2.66000000e+02, 1.90000000e+02,
        1.14000000e+02, 3.08000000e+02, 2.20000000e+02, 1.32000000e+02,
        3.50000000e+02, 2.50000000e+02, 1.50000000e+02, 3.92000000e+02,
        2.80000000e+02, 1.68000000e+02, 4.34000000e+02, 3.10000000e+02,
        1.86000000e+02, 4.76000000e+02, 3.40000000e+02, 2.04000000e+02,
        5.18000000e+02, 3.70000000e+02, 2.22000000e+02, 5.60000000e+02,
        4.00000000e+02, 2.40000000e+02, 6.02000000e+02, 4.30000000e+02,
        2.58000000e+02, 6.44000000e+02, 4.60000000e+02, 2.76000000e+02,
        6.86000000e+02, 4.90000000e+02, 2.94000000e+02],
       [3.16227766e+01, 3.16543836e+01, 3.16859590e+01, 3.17175031e+01,
       

In [134]:
your_array = np.random.randn(6,3)

i = 1

a=your_array[:, i:i+1]

In [135]:
your_array

array([[ 0.87373551,  0.33450474,  1.06399277],
       [ 1.91992861,  0.67940908, -2.99943945],
       [ 0.01292765,  0.59452153, -0.20935598],
       [-0.03857844, -0.25719379, -2.1452384 ],
       [-1.97822269, -0.0852396 , -0.70754557],
       [ 1.03230709, -1.4809075 ,  0.91208553]])

In [136]:
a

array([[ 0.33450474],
       [ 0.67940908],
       [ 0.59452153],
       [-0.25719379],
       [-0.0852396 ],
       [-1.4809075 ]])

In [137]:

#Чему равна сумма элементов последнего столбца массива? Ответ округлите до двух цифр после запятой:
round(big_secret[:,50].sum(),2)

3154.33

In [138]:
#Выделите из каждой строки массива big_secret первые 5 элементов. Чему равна сумма элементов главной диагонали получившейся матрицы? #Округлите ответ до двух цифр после запятой:
diag = np.diag(big_secret[:, :5])
round(diag.sum(),2)

121.37

Выделите из каждой строки массива big_secret последние 5 элементов. Чему равно произведение элементов главной диагонали получившейся матрицы? Введите полученный результат без изменений и округлений.

У меня есть одномерный массив NumPy:
a = numpy.array([2,3,3])
Я хотел бы иметь произведение всех элементов, в данном случае 18.
Единственный способ, который я мог бы найти, чтобы сделать это, был бы:
b = reduce(lambda x,y: x*y, a)
другие варианты
reduce(lambda x,y: x*y, a) -- 24.2µs,

numpy.prod(a) -- 3.9µs.

 a.prod() -- 2.67µs.


In [139]:
diag = np.diag(big_secret[:, -5:])
diag.prod()

341505315559.2347

In [140]:
#Создадим массив 4 х 6:
my_array = np.random.randint(1, 100, (4, 6)) 
my_array

array([[96, 21,  8, 75, 61, 48],
       [73, 86, 97, 15, 37,  4],
       [92, 78, 78, 34, 57, 78],
       [25, 63,  7, 13, 86, 57]])

Выделим из созданного массива квадрат 2 х 2, содержащий 4 элемента, расположенные в центре матрицы:

In [141]:
my_slice = my_array[1:3, 2:4]
my_slice

array([[97, 15],
       [78, 34]])

Заменим эти элементы на нули и посмотрим, как изменится содержимое исходной матрицы:

In [142]:
my_slice[:] = 0
my_array

array([[96, 21,  8, 75, 61, 48],
       [73, 86,  0,  0, 37,  4],
       [92, 78,  0,  0, 57, 78],
       [25, 63,  7, 13, 86, 57]])

In [143]:
sl2 = my_array[::2,::2]
sl2[:]=-1
my_array

array([[-1, 21, -1, 75, -1, 48],
       [73, 86,  0,  0, 37,  4],
       [-1, 78, -1,  0, -1, 78],
       [25, 63,  7, 13, 86, 57]])

In [144]:
sl2 = my_array[1::2,1::2]
sl2[:]=1
my_array

array([[-1, 21, -1, 75, -1, 48],
       [73,  1,  0,  1, 37,  1],
       [-1, 78, -1,  0, -1, 78],
       [25,  1,  7,  1, 86,  1]])

In [145]:
big2 = big_secret[::2, ::2]
big2[:] = -1

In [146]:
big1 = big_secret[1::2, 1::2]
big1[:] = 1

In [153]:
big_secret[:,:5].diagonal().sum()

-1.0

In [156]:
ndiag = np.diag(big_secret[:, -5:])
ndiag.prod()



-1.0

Особенностью работы с массивами в NumPy является то, что возможности библиотеки позволяют выполнять любые математические действия с массивами без использования циклов for, благодаря чему вычисления производятся с большой скоростью. В NumPy над массивами можно производить все стандартные арифметические операции.

Операции выполняются поэлементно, поэтому для получения корректного результата размерность массивов должна быть одинаковой. Также можно производить математические операции между массивом и числом.

У нас есть два массива: найдём их сумму, разность, произведение, частное и умножим один из массивов на число:

In [159]:
a = np.array([3,6,9])
b = np.array([12,15,18])

result1 = a+b
result2 = b-a
result3 = a*b
result4 = a/b
result5 = a*2
print('Сумма: {}\nРазность: {}\nПроизведение: {}\nЧастное: {}\nУмножение на число: {}'.format(result1, result2, result3, result4, result5))

Сумма: [15 21 27]
Разность: [9 9 9]
Произведение: [ 36  90 162]
Частное: [0.25 0.4  0.5 ]
Умножение на число: [ 6 12 18]


Универсальные функции
Универсальными называют функции, которые выполняют поэлементные операции над данными, хранящимися в объектах ndarray.  Большинство универсальных функций относятся к унарным операциям и выполняются над каждым элементом массива по очереди. Унарные операции — это  и есть операции, которые выполняются над каждым элементом массива по очереди.

Рассмотрим список часто используемых универсальных функций NumPy. При вызове каждой из этих функций необходимо указывать название библиотеки NumPy: np.isnan(имя_массива):

Функция	Описание
abs	Абсолютное значение целых, вещественных или комплексных элементов массива
sqrt	Квадратный корень каждого элемента массива
exp	Экспонента (ex) каждого элемента массива
log, log10, log2, log1p	Натуральный (по основанию е), десятичный, двоичный логарифм и функция log(1+x) соответственно
modf	Дробные и целые части массива в виде отдельных массивов
isnan	Массив логических (булевых) значений, показывающий, какие из элементов исходного массива  являются NaN (не числами)
cos, sin, tan	Обычные тригонометрические функции
arccos, arcsin, arctan	Обратные тригонометрические функции

Изменение размерности массива
В некоторых задачах машинного обучения для подготовки данных к обработке нужно изменить исходную форму массива, например, преобразовать многомерный массив в одномерный, поменять местами строки и столбцы.

Замена местами строк и столбцов двумерного массива называется транспонированием. Для выполнения этой операции в NumPy используется метод T:

In [160]:
my_array = np.array([[1,2,3,4,5], [6,7,8,9,10]])
my_array.T

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

Для превращения массива одной размерности в массив другой — обычно для преобразования одномерного массива в многомерный — используется метод reshape. Изменить размерность массива можно только в том случае, если число элементов в исходном и в целевом массиве совпадает:

In [162]:
my_array = np.random.randint(0, 10, 20)
my_array

array([0, 2, 3, 2, 4, 8, 6, 1, 5, 6, 7, 3, 3, 9, 7, 6, 8, 9, 4, 7])

In [165]:
my_array.reshape((5,4))

array([[0, 2, 3, 2],
       [4, 8, 6, 1],
       [5, 6, 7, 3],
       [3, 9, 7, 6],
       [8, 9, 4, 7]])

Для преобразования многомерного массива в одномерный используется метод flatten:

In [167]:
my_array = np.array([[1,2,3], [11,22,33], [111,222,333]])
my_array


array([[  1,   2,   3],
       [ 11,  22,  33],
       [111, 222, 333]])

In [168]:
my_array.flatten()

array([  1,   2,   3,  11,  22,  33, 111, 222, 333])

In [169]:
my_array.reshape((3,3))

array([[  1,   2,   3],
       [ 11,  22,  33],
       [111, 222, 333]])

Научимся сравнивать элементы массива с числом и извлекать из него только те элементы, которые больше или меньше заданного числа. Для этого создадим массив размера 3х4, произвольно заполненный числами от 0 до 10. 

In [170]:
my_array = np.random.randint(0, 10, (3,4))

In [171]:
my_array

array([[6, 7, 6, 6],
       [0, 0, 1, 7],
       [6, 7, 7, 7]])

In [172]:
my_array<5

array([[False, False, False, False],
       [ True,  True,  True, False],
       [False, False, False, False]])

Мы получили новый массив, заполненный значениями True/False в зависимости от того, меньше или больше пяти элемент, находящийся на соответствующей позиции в исходном массиве. Для того, чтобы получить элементы массива my_array, которые меньше пяти, воспользуемся кодом ниже. Отобранные элементы представляют собой одномерный массив.

In [173]:
my_array[my_array<5]

array([0, 0, 1])

Маска нужна для выбора только определенных строк или столбцов из всего массива и скрытия остальных. Маска в Python задаётся при помощи булевых 0 и 1, где 0 скрывает столбец или строку, а 1 оставляет ее на виду. Выведем первый и третрий столбец массива:

In [174]:
mask = np.array([1, 0, 1, 0], dtype=bool)
my_array[:, mask]

array([[6, 6],
       [0, 1],
       [6, 7]])

В двумерных массивах можно выполнять сортировку элементов строк и столбцов:

Сортировка выполняется с помощью функции sort, в качестве параметров функция получает сам массив, а также номер оси (0 (для столбцов) или 1 (для строк)) , элементы которой необходимо отсортировать. 

Как можно отсортировать элементы строк и столбцов?

Отсортируем элементы строк:

In [202]:
my_array = np.random.randint(0, 10, (4, 6))
my_array


array([[9, 6, 6, 7, 0, 5],
       [3, 2, 5, 4, 2, 5],
       [4, 2, 0, 5, 4, 1],
       [9, 0, 7, 6, 6, 6]])

In [203]:
my_array[:,0]

array([9, 3, 4, 9])

In [239]:
#np.sort(my_array, ) 
np.sort(my_array, axis=1)

array([[0, 5, 6, 6, 7, 9],
       [2, 2, 3, 4, 5, 5],
       [0, 1, 2, 4, 4, 5],
       [0, 6, 6, 6, 7, 9]])

In [194]:
np.sort(my_array, axis=0) #np.sort(my_array, axis=-2)


array([[0, 5, 1, 1, 0, 1],
       [4, 7, 2, 2, 0, 5],
       [4, 8, 4, 4, 7, 6],
       [8, 9, 8, 5, 8, 7]])

In [205]:
first = [x**(1/2) for x in range(100)]
second = [x**(1/3) for x in range(100, 200)]
third = [x/y for x in range(200,300,2) for y in [3,5]]

great_secret = np.array([first, second, third]).T



In [212]:
great_secret[:0]

array([], shape=(0, 3), dtype=float64)

In [197]:
great_secret.shape

(100, 3)

In [204]:
great_secret[:0]

array([], shape=(0, 3), dtype=float64)

Чему равна сумма косинусов элементов первой строки массива great_secret? Ответ округлите до двух знаков после запятой

In [227]:
round(np.cos(great_secret[0]).sum(),2)


0.16

In [230]:
#Чему равна сумма элементов массива great_secret, значение которых больше 50?
great_secret[great_secret>50].sum()

5470.0

Переведите массив great_secret в одномерную форму. Какое значение в получившемся массиве имеет элемент с индексом 150? Скопируйте ответ из Jupyter Notebook без изменений.

In [235]:

great_secret.flatten()[150]



7.0710678118654755

Отсортируйте значения столбцов массива great_secret по возрастанию. Чему равна сумма элементов последней строки отсортированного массива? Ответ округлите до двух цифр после запятой.

In [247]:
round(np.sort(great_secret, axis=0)[-1].sum(), 2)

115.12

Математические и статистические операции
Модуль NumPy содержит множество базовых статистических функций, которые помогают описать имеющиеся данные: среднее арифметическое (mean), медиана (median), стандартное отклонение (std), корреляция (corrcoef) и прочие. Давайте посмотрим, как они работают. 

Для изучения функций будем использовать набор данных, содержащих информацию об учениках шестого класса. Данные об учениках представлены в таблице:

ID (номер в журнале)	Рост, см	Масса тела, кг	Средний балл
1	135	34	4
2	160	43	5
3	163	40	4.3
4	147	44	5
5	138	41	4.7
6	149	54	3.9
7	136	39	4.2
8	154	48	4.9
9	137	35	3.7
10	165	60	4.6
Создайте массив, содержащий эти данные, и сохраните его под именем students.

In [272]:
studentm = np.matrix ('1	135	34	4; 2	160	43	5; 3	163	40	4.3; 4	147	44	5; 5	138	41	4.7; 6	149	54	3.9; 7	136	39	4.2; 8	154	48	4.9; 9	137	35	3.7; 10	165	60	4.6' )

In [273]:
studentm

matrix([[  1. , 135. ,  34. ,   4. ],
        [  2. , 160. ,  43. ,   5. ],
        [  3. , 163. ,  40. ,   4.3],
        [  4. , 147. ,  44. ,   5. ],
        [  5. , 138. ,  41. ,   4.7],
        [  6. , 149. ,  54. ,   3.9],
        [  7. , 136. ,  39. ,   4.2],
        [  8. , 154. ,  48. ,   4.9],
        [  9. , 137. ,  35. ,   3.7],
        [ 10. , 165. ,  60. ,   4.6]])

In [274]:
stud = student.flatten()

In [275]:
stud

matrix([[  1. , 135. ,  34. ,   4. ,   2. , 160. ,  43. ,   5. ,   3. ,
         163. ,  40. ,   4.3,   4. , 147. ,  44. ,   5. ,   5. , 138. ,
          41. ,   4.7,   6. , 149. ,  54. ,   3.9,   7. , 136. ,  39. ,
           4.2,   8. , 154. ,  48. ,   4.9,   9. , 137. ,  35. ,   3.7,
          10. , 165. ,  60. ,   4.6]])

In [279]:
students = np.array([[  1. , 135. ,  34. ,   4. ],
        [  2. , 160. ,  43. ,   5. ],
        [  3. , 163. ,  40. ,   4.3],
        [  4. , 147. ,  44. ,   5. ],
        [  5. , 138. ,  41. ,   4.7],
        [  6. , 149. ,  54. ,   3.9],
        [  7. , 136. ,  39. ,   4.2],
        [  8. , 154. ,  48. ,   4.9],
        [  9. , 137. ,  35. ,   3.7],
        [ 10. , 165. ,  60. ,   4.6]])

In [280]:
students

array([[  1. , 135. ,  34. ,   4. ],
       [  2. , 160. ,  43. ,   5. ],
       [  3. , 163. ,  40. ,   4.3],
       [  4. , 147. ,  44. ,   5. ],
       [  5. , 138. ,  41. ,   4.7],
       [  6. , 149. ,  54. ,   3.9],
       [  7. , 136. ,  39. ,   4.2],
       [  8. , 154. ,  48. ,   4.9],
       [  9. , 137. ,  35. ,   3.7],
       [ 10. , 165. ,  60. ,   4.6]])

Среднее арифметическое (mean) — сумма всех значений, делённая на их количество, показывает общую тенденцию данных и описывает их одним числом. Узнаем среднюю успеваемость школьников в классе, используя функцию mean:

In [281]:
mean = np.mean(students[:,-1])
mean


4.430000000000001

Медиана — это такое число, что ровно половина элементов из выборки больше него, а другая половина меньше него. Если в выборке есть выбросы (значения, которые принимают величину существенно выше или ниже среднего и выделяются из всей выборки), то медиана будет лучше характеризовать всю выборку, чем среднее арифметическое.

Узнаем, как учится средний ученик, с помощью функции median:

In [282]:
median = np.median(students[:,-1])
median


4.449999999999999

Заметим, что школьников в выборке всего 10, а медиана — это значение выборки, при котором ровно половина значений меньше неё, а половина — больше. 

Таким образом, при вычислении медианы Python сначала упорядочит значения по возрастанию, а затем возьмет среднее из серединных элементов полученного ряда. В нашем случае это будут пятый и шестой элементы. Мы можем это проверить, используя функцию sort для сортировки значений оценок: 

In [283]:
sort = np.sort(students[:,-1])
(sort[4]+sort[5])/2

4.449999999999999

In [286]:
sort[5]

4.6

In [289]:
#медианное значение массы тела школьников
np.median(students[:,-2])

42.0

На сколько среднее арифметическое массы тела школьников больше медианного значения для этого же показателя? Дайте ответ в килограммах с точностью до одной десятой кг.

In [291]:
round(np.mean(students[:, -2]) - np.median(students[:, -2]), 1)

1.8

Корреляция — статистическая взаимосвязь случайных величин. Мерой корреляции служит одноименный коэффициент, который показывает, насколько сильно связаны величины, он может быть положительным или отрицательным, а по модулю принимает значение от 0 до 1. Отрицательный коэффициент говорит о том, что случайные величины связаны, но при увеличении одной из них вторая уменьшается. Если коэффициент положительный, то величины изменяются в одном направлении.

Аналитики часто оперируют в своей работе данной величиной и ошибаются, делая ложные выводы о данных. Связано это с тем, что не всегда наличие корреляции между двумя показателями говорит о том, что между ними есть причинно-следственная связь.

Давайте узнаем, как связан рост и вес наших школьников, посчитав коэффициент корреляции столбцов матрицы:

In [292]:
corr = np.corrcoef(students[:,1], students[:,2])
corr

array([[1.        , 0.64314431],
       [0.64314431, 1.        ]])

In [293]:
np.corrcoef(students[:,1], students[:,3])

array([[1.        , 0.46293714],
       [0.46293714, 1.        ]])

In [294]:
np.corrcoef(students[:,3], students[:,2])

array([[1.        , 0.29801325],
       [0.29801325, 1.        ]])

Показатели вариации
Математическое ожидание — среднее значение случайной величины при стремлении числа её измерений к бесконечности. Если число измерений конечно, то для оценки среднего значения величины используется среднее арифметическое. 

Дисперсия — мера разброса случайной величины относительно её математического ожидания. 

 {\displaystyle D[X]=M\left[{\big (}X-M[X]{\big )}^{2}\right]} 

Как следует из формулы, дисперсия случайной величины X равна математическому ожиданию квадрата отклонения случайной величины от ее математического ожидания. То есть, если величина дисперсии небольшая, значит, все числа в выборке имеют близкие друг к другу значения, а чем она больше — тем значительнее разброс показателей.

Стандартное отклонение — самый распространенный показатель рассеивания случайной величины относительно её математического ожидания. 

{\displaystyle \sigma ={\sqrt {D[X]}}}.

Стандартное отклонение равно квадратному корню из дисперсии. Низкое стандартное отклонение показывает, что все значения в выборке сгруппированы около среднего значения.  Большой показатель этой величины говорит о том, что разброс значений большой. 

Узнаем, насколько разный у школьников рост, посчитав стандартное отклонение std:

In [295]:
std = np.std(students[:,1])
std

11.083320801997928

In [296]:
np.std(students[:,-1])

0.4517742799230607

Посчитайте, чему равна дисперсия значений веса школьников.

Эту величину можно получить двумя способами: математически - используя определение дисперсии и известную функцию в блоке, или самостоятельно - используя подходящую функцию модуля NumPy.

In [297]:

np.std(students[:,2])**2

60.36

In [298]:
np.var(students[:, 2])

60.36