In [2]:
import numpy as np

In [3]:
#создадим матрицу, которая нам понадобится в работе.
m = np.matrix('1 2 3 4; 5 6 7 8 ; 9 1 5 7')

In [4]:
print(m)

[[1 2 3 4]
 [5 6 7 8]
 [9 1 5 7]]


In [5]:
type(m)


numpy.matrix

In [6]:
#Matix можно превратить в ndarray вот так
m = np.array(m)

In [7]:
type(m)

numpy.ndarray

In [8]:
print(m)

[[1 2 3 4]
 [5 6 7 8]
 [9 1 5 7]]


In [9]:
#Для определения размерности массива Numpy используйте атрибут shape
m.shape

(3, 4)

In [10]:
m.max()
np.max(m)

9

In [11]:
m.max(axis=1)

array([4, 8, 9])

In [12]:
m.max(axis=0)

array([9, 6, 7, 8])

In [13]:
m

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 1, 5, 7]])

In [14]:
m

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 1, 5, 7]])