In [15]:
import numpy as np

In [16]:
#создадим матрицу, которая нам понадобится в работе.
m = np.matrix('1 2 3 4; 5 6 7 8 ; 9 1 5 7')

In [17]:
print(m)

[[1 2 3 4]
 [5 6 7 8]
 [9 1 5 7]]


In [18]:
type(m)


numpy.matrix

In [19]:
#Matix можно превратить в ndarray вот так
m = np.array(m)

In [20]:
type(m)

numpy.ndarray

In [21]:
print(m)

[[1 2 3 4]
 [5 6 7 8]
 [9 1 5 7]]


In [22]:
#Для определения размерности массива Numpy используйте атрибут shape
m.shape

(3, 4)

In [23]:
m.max()
np.max(m)

9

In [24]:
m.max(axis=1)

array([4, 8, 9])

In [25]:
m.max(axis=0)

array([9, 6, 7, 8])

In [26]:
m

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 1, 5, 7]])

In [27]:
m

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 1, 5, 7]])

kkk